//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlliedSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ShoppingItems = new HashSet<ShoppingItem>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public long Price { get; set; }
        public long Quantity { get; set; }
    
        public virtual ICollection<ShoppingItem> ShoppingItems { get; set; }
    }
}
